### ISSUE TITLE
Update README.md for developers and MCP users

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-mcp#6]
The README.md currently implies that there is a `uv pip install -e ".[dev]"` step. I got a warning when I did that. 

> warning: The package `nmdc-mcp @ file:///home/mark/gitrepos/microbiomedata/nmdc-mcp` does not have an extra named `dev`

Maybe something like this would be better?

```shell
uv sync --group dev
```

I also doesn't address the required MCP client setup. That can be done graphically, but for those who like to edit their Goose (`~/.config/goose/config.yaml`) or Claude code config files, this is the general idea:

```yaml
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  nmdc_mcp_server:
    args:
      - ~/gitrepos/microbiomedata/nmdc-mcp/src/nmdc_mcp/main.py
    bundled: null
    cmd: ~/gitrepos/microbiomedata/nmdc-mcp/.venv/bin/python
    description: MCP server for NMDC using nmdc-mcp
    enabled: true
    env_keys: []
    envs: {}
    name: nmdc_mcp_server
    timeout: 300
    type: stdio
```

You may need to expand `~` to the full path like `/home/mark/`
